### ISSUE TITLE
release in pypi

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/django-tidb#4]
The Python community is used to using pip to manage dependencies

So release `django-tidb` to pypi is a better option

**Comment by hawkingrei** [comment]
Thank you for your suggestion. we plan to release ```django-tidb``` to pypi after we complete to deploy CI/CD and the test with a different versions of TiDB.

**Comment by Allan-Nava** [comment]
Any news?

**Comment by zhangyangyu** [comment]
`django-tidb` has published on PyPi as 3.0.0. Check https://github.com/pingcap/django-tidb/blob/main/README.md.
