### ISSUE TITLE
When adding a OneToOneField field, it is not supported during migration.

### ISSUE THREAD

**Issue by wangyushun** [pingcap/django-tidb#48]
When adding a OneToOneField field, it is not supported during migration. 
I got an error like "OperationalError: (8200, "unsupported add column 'x_id' constraint UNIQUE KEY when altering 'x')".
Is there any elegant solution?

use:
TiDB 7.1.1
Django 4.2.4
django-tidb 4.2

**Comment by wd0517** [comment]
TiDB does not support multiple operations with a single DDL statement, see  [MySQL Compatibility - DDL operations
](https://docs.pingcap.com/tidb/dev/mysql-compatibility#ddl-operations), it is the reason for the error you encountered. Additionally, adding a new field in Django with `unique=True` will also [fail](https://github.com/pingcap/tidb/issues/30188).

To resolve this issue, I will try to separating the SQL into multiple DDL statements. First, add the column and then add the unique constraint and foreign key.

If you need a temporary workaround before the fix, you can do multiple migrations. First, add `models.ForeignKey('x', on_delete=models.CASCADE)` and create a migration. Then, change it to `models.OneToOneField('x', on_delete=models.CASCADE)` and create a second migration. Finally, apply both migrations.

**Comment by wangyushun** [comment]
I got it, thanks. Looking forward to your contribution.

**Comment by wd0517** [comment]
@wangyushun This issue has been resolved in `django-tidb==v4.2.1`
