### ISSUE TITLE
Support `AUTO_RANDOM`

### ISSUE THREAD

**Issue by wd0517** [pingcap/django-tidb#51]
[`auto_random`](https://docs.pingcap.com/tidb/stable/auto-random) is a feature in TiDB that generates unique IDs for a table automatically. It is similar to `auto_increment` in MySQL, but it can avoid the write hotspot issue caused by `auto_increment`.

## How
1. Create a new class called `BigAutoRandomField` that inherits from the existing `BigAutoField` class. You can find the implementation of `BigAutoField` [here](https://github.com/django/django/blob/main/django/db/models/fields/__init__.py#L2861).
2. In the `DatabaseWrapper`, define the data type for this new field (`BigAutoRandomField`).
3. Finally, in your project's `settings.py`, set the value of `DEFAULT_AUTO_FIELD` to `'django_db.fields.BigAutoRandomField'`. This will enable the auto_random feature.

@zhangyangyu @dveeden PTAL

**Comment by zhangyangyu** [comment]
LGTM
